version: "3.8"

services:
  app:
    container_name: loans-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    command: ["uvicorn", "app.api:loans_api", "--host", "0.0.0.0", "--port", "8000"]
