name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your primary branch

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Path to your Dockerfile
          outputs: |
            type=registry
            image=ghcr.io/${{ github.repository_owner }}/loans-api:latest  # Temporary placeholder
          push: false  # Don't push to a registry

      - name: Save Docker image as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ${{ steps.build.outputs.image }}

      - name: Logout from Docker Hub (if logged in)
        run: docker logout || true
