name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your primary branch

jobs:
  build-and-store:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ steps.build.outputs.image }}

      - name: Logout from Docker Hub (if logged in)
        run: docker logout || true
