name: CI/CD Pipeline

on:
  release:
    types: [published]

jobs:
  build-and-store:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cristian-rincon/loans-api:latest
            cristian-rincon/loans-api:{{ github.ref }}
            ghcr.io/cristian-rincon/loans-api:latest
            ghcr.io/cristian-rincon/loans-api:{{ github.ref }}